project_id = "unglish-review"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.seed]
enabled = false

[studio]
enabled = false

[local_smtp]
enabled = false

[storage]
enabled = false

[auth]
enabled = true
enable_signup = false
enable_anonymous_sign_ins = false

[realtime]
enabled = false

[analytics]
enabled = false

[edge_runtime]
enabled = false
