export const stopGraphemes = [
    // pig
    { phoneme: "p",
        form: "p",
        origin: 3,
        frequency: 50,
        startWord: 1,
        midWord: 1,
        endWord: 1,
    },
    // b boy
    { phoneme: "b",
        form: "b",
        origin: 3,
        frequency: 100,
        startWord: 1,
        midWord: 1,
        endWord: 1, },
    {
        phoneme: "b",
        form: "pb",
        origin: 3,
        frequency: 1,
        onset: 0,
        cluster: 0,
        startWord: 0,
        midWord: 1,
        endWord: 0,
    },
    // t top
    { phoneme: "t", form: "t", origin: 3, frequency: 2500, startWord: 1,
        midWord: 1,
        endWord: 1, },
    { phoneme: "t",
        form: "th",
        origin: 2,
        frequency: 1,
        coda: 0,
        cluster: 0,
        startWord: 0,
        midWord: 1,
        endWord: 1, },
    {
        phoneme: "t",
        form: "bt",
        origin: 3,
        frequency: 1,
        onset: 0,
        cluster: 0,
        startWord: 0,
        midWord: 1,
        endWord: 1,
    },
    {
        phoneme: "t",
        form: "ed",
        origin: 3,
        frequency: 2,
        onset: 0,
        startWord: 0,
        midWord: 0,
        endWord: 1,
    },
    // d dog
    { phoneme: "d",
        form: "d",
        origin: 3,
        frequency: 300,
        startWord: 1,
        midWord: 1,
        endWord: 1, },
    {
        phoneme: "d",
        form: "ed",
        origin: 3,
        frequency: 6,
        onset: 0,
        cluster: 300,
        startWord: 0,
        midWord: 0,
        endWord: 1,
    },
    // k: before front vowels (keep, kind)
    { phoneme: "k",
        form: "k",
        origin: 3,
        frequency: 50,
        startWord: 1,
        midWord: 1,
        endWord: 10,
        condition: { rightContext: ["c-soft-vowel"] },
    },
    // k: word-final (speak, back)
    { phoneme: "k",
        form: "k",
        origin: 3,
        frequency: 50,
        startWord: 1,
        midWord: 1,
        endWord: 10,
        condition: { wordPosition: ["final"] },
    },
    // c: before back vowels and consonants (cat, cold, cup, craft)
    { phoneme: "k",
        form: "c",
        origin: 3,
        frequency: 60,
        cluster: 100,
        startWord: 1,
        midWord: 1,
        endWord: 0,
        condition: { notRightContext: ["c-soft-vowel"] },
    },
    {
        phoneme: "k",
        form: "ck",
        origin: 3,
        frequency: 100,
        onset: 0,
        startWord: 0,
        midWord: 1,
        endWord: 10,
        condition: { leftContext: ["lax-vowel"] },
    },
    {
        phoneme: "k",
        form: "ch",
        origin: 3,
        frequency: 2,
        startWord: 1,
        midWord: 1,
        endWord: 1,
        condition: {
            rightContext: ["vowel", "r", "l"],
        },
    },
    {
        phoneme: "k",
        form: "lk",
        origin: 3,
        frequency: 4,
        onset: 0,
        startWord: 0,
        midWord: 1,
        endWord: 1,
    },
    {
        phoneme: "k",
        form: "q",
        origin: 3,
        frequency: 1,
        onset: 0,
        startWord: 1,
        midWord: 1,
        endWord: 1,
    },
    // g: go
    { phoneme: "g",
        form: "g",
        origin: 3,
        frequency: 100,
        startWord: 1,
        midWord: 1,
        endWord: 1,
        condition: { notRightContext: ["front-vowel"] },
    },
    {
        phoneme: "g",
        form: "gh",
        origin: 3,
        frequency: 2,
        coda: 0,
        cluster: 0,
        startWord: 1,
        midWord: 0,
        endWord: 0,
    },
    {
        phoneme: "g",
        form: "gu",
        origin: 3,
        frequency: 5,
        coda: 0,
        startWord: 1,
        midWord: 1,
        endWord: 0,
    },
    {
        phoneme: "g",
        form: "gue",
        origin: 3,
        frequency: 3,
        onset: 0,
        startWord: 0,
        midWord: 1,
        endWord: 1,
    },
    // Example: "fire", "tire", "wire"
    {
        phoneme: "aɪə",
        form: "ire",
        origin: 0,
        frequency: 50,
        startWord: 3,
        midWord: 1,
        endWord: 100,
    },
    // Example: "liar", "prior"
    {
        phoneme: "aɪə",
        form: "ia",
        origin: 0,
        frequency: 30,
        startWord: 2,
        midWord: 1,
        endWord: 80,
    },
    // Example: "buyer", "flyer"
    {
        phoneme: "aɪə",
        form: "ye",
        origin: 0,
        frequency: 20,
        startWord: 2,
        midWord: 1,
        endWord: 70,
    },
    // Example: "choir"
    {
        phoneme: "aɪə",
        form: "oi",
        origin: 1,
        frequency: 5,
        startWord: 1,
        midWord: 1,
        endWord: 50,
    },
    // Example: "science", "client"
    {
        phoneme: "aɪə",
        form: "ie",
        origin: 3,
        frequency: 10,
        startWord: 3,
        midWord: 2,
        endWord: 0,
    },
    // Example: "hour", "flour"
    {
        phoneme: "aʊə",
        form: "ou",
        origin: 1,
        frequency: 50,
        startWord: 2,
        midWord: 1,
        endWord: 100,
    },
    // Example: "shower", "power"
    {
        phoneme: "aʊə",
        form: "owe",
        origin: 0,
        frequency: 40,
        startWord: 1,
        midWord: 1,
        endWord: 100,
    },
    // Example: "player", "layer"
    {
        phoneme: "eɪə",
        form: "aye",
        origin: 0,
        frequency: 50,
        startWord: 2,
        midWord: 1,
        endWord: 100,
    },
    // Example: "mayor", "prayer"
    {
        phoneme: "eɪə",
        form: "ayo",
        origin: 0,
        frequency: 30,
        startWord: 2,
        midWord: 1,
        endWord: 80,
    },
    // Example: "conveyor"
    {
        phoneme: "eɪə",
        form: "eyo",
        origin: 0,
        frequency: 10,
        startWord: 0,
        midWord: 1,
        endWord: 100,
    },
    // Example: "employer", "destroyer"
    {
        phoneme: "ɔɪə",
        form: "oye",
        origin: 1,
        frequency: 50,
        startWord: 2,
        midWord: 1,
        endWord: 100,
    },
    // Example: "loyal", "royal"
    {
        phoneme: "ɔɪə",
        form: "oya",
        origin: 1,
        frequency: 40,
        startWord: 1,
        midWord: 1,
        endWord: 100,
    },
    // Example: "lower", "mower"
    {
        phoneme: "əʊə",
        form: "owe",
        origin: 0,
        frequency: 50,
        startWord: 1,
        midWord: 2,
        endWord: 100,
    },
    // Example: "Noah"
    {
        phoneme: "əʊə",
        form: "oa",
        origin: 4,
        frequency: 10,
        startWord: 1,
        midWord: 0,
        endWord: 100,
    },
    // Example: "boa"
    {
        phoneme: "əʊə",
        form: "oa",
        origin: 0,
        frequency: 5,
        startWord: 1,
        midWord: 0,
        endWord: 100,
    },
];
