/** Affricate graphemes: /tʃ/ (ch), /dʒ/ (j). */
import { Grapheme, GraphemeCondition } from "../../types.js";

export const affricateGraphemes: Grapheme[] = [
  // cheese
  {
    phoneme: "tʃ",
    form: "ch",
    origin: 3,
    frequency: 140,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "tʃ",
    form: "tch",
    origin: 0,
    frequency: 30,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
    condition: { leftContext: ["lax-vowel"] },
  },
  {
    phoneme: "tʃ",
    form: "tu",
    origin: 3,
    frequency: 1,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  // righteous
  {
    phoneme: "tʃ",
    form: "te",
    origin: 3,
    frequency: 1,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // d�� judge
  {
    phoneme: "dʒ",
    form: "g",
    origin: 3,
    frequency: 15,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 0,
    condition: { rightContext: ["front-vowel"] },
  },
  {
    phoneme: "dʒ",
    form: "j",
    origin: 3,
    frequency: 20,
    coda: 0,
    cluster: 0,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "dʒ",
    form: "ge",
    origin: 3,
    frequency: 6,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "dʒ",
    form: "dge",
    origin: 3,
    frequency: 10,
    onset: 0,
    startWord: 0,
    midWord: 1,
    endWord: 1,
    condition: { leftContext: ["lax-vowel"] },
  },
  {
    phoneme: "dʒ",
    form: "di",
    origin: 3,
    frequency: 1,
    onset: 0,
    startWord: 0,
    midWord: 1,
    endWord: 0,
    condition: { notRightContext: ["front-vowel"] },
  },
  {
    phoneme: "dʒ",
    form: "gg",
    origin: 3,
    frequency: 1,
    onset: 0,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  }
];
