/**
 * Fricative graphemes.
 * 
 * Fricatives are consonants produced by forcing air through a narrow channel:
 * - f (fish), v (van)
 * - θ (thin), ð (this)
 * - s (sun), z (zebra)
 * - ʃ (she), ʒ (measure)
 * - h (hat)
 */

import { Grapheme } from "../../types.js";

export const fricativeGraphemes: Grapheme[] = [
  // f: fish
  {
    phoneme: "f",
    form: "f",
    origin: 3,
    frequency: 100,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "f",
    form: "ph",
    origin: 2,
    frequency: 1,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "f",
    form: "gh",
    origin: 0,
    frequency: 1,
    onset: 0,
    startWord: 0,
    midWord: 1,
    endWord: 1,
  },

  // v: van
  {
    phoneme: "v",
    form: "v",
    origin: 3,
    frequency: 100,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "v",
    form: "f",
    origin: 3,
    frequency: 1,
    startWord: 0,
    midWord: 0,
    endWord: 25,
  },
  {
    phoneme: "v",
    form: "ve",
    origin: 3,
    onset: 0,
    frequency: 1,
    startWord: 0,
    midWord: 0,
    endWord: 50,
  },
  {
    phoneme: "v",
    form: "ph",
    origin: 2,
    frequency: 1,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // θ: thin
  {
    phoneme: "θ",
    form: "th",
    origin: 2,
    frequency: 10,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // ð: this
  {
    phoneme: "ð",
    form: "th",
    origin: 2,
    frequency: 10,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // s: sun
  {
    phoneme: "s",
    form: "s",
    origin: 3,
    frequency: 1000,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "s",
    form: "c",
    origin: 3,
    frequency: 2,
    cluster: 0,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "s",
    form: "sc",
    origin: 3,
    frequency: 2,
    coda: 0,
    cluster: 0,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "s",
    form: "ps",
    origin: 2,
    frequency: 1,
    coda: 0,
    cluster: 0,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "s",
    form: "st",
    origin: 0,
    frequency: 2,
    coda: 0,
    cluster: 0,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "s",
    form: "ce",
    origin: 3,
    frequency: 3,
    onset: 0,
    cluster: 0,
    startWord: 0,
    midWord: 0,
    endWord: 1,
  },
  {
    phoneme: "s",
    form: "se",
    origin: 3,
    frequency: 3,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // z: zebra
  {
    phoneme: "z",
    form: "z",
    origin: 3,
    frequency: 1000,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "z",
    form: "s",
    origin: 3,
    frequency: 100,
    onset: 0,
    startWord: 0,
    midWord: 100,
    endWord: 1,
  },
  {
    phoneme: "z",
    form: "x",
    origin: 3,
    frequency: 1,
    coda: 0,
    startWord: 1,
    midWord: 0,
    endWord: 0,
  },
  {
    phoneme: "z",
    form: "ze",
    origin: 3,
    frequency: 4,
    onset: 0,
    startWord: 0,
    midWord: 0,
    endWord: 1,
  },
  {
    phoneme: "z",
    form: "se",
    origin: 3,
    frequency: 1,
    onset: 0,
    startWord: 0,
    midWord: 0,
    endWord: 1,
  },

  // ʃ: she
  {
    phoneme: "ʃ",
    form: "sh",
    origin: 0,
    frequency: 750,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "ti",
    origin: 3,
    frequency: 80,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "ci",
    origin: 3,
    frequency: 50,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "ch",
    origin: 3,
    frequency: 30,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "s",
    origin: 3,
    frequency: 20,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "si",
    origin: 3,
    frequency: 20,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "ce",
    origin: 3,
    frequency: 8,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "ssi",
    origin: 3,
    frequency: 7,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "sc",
    origin: 3,
    frequency: 10,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "xi",
    origin: 3,
    frequency: 10,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʃ",
    form: "sch",
    origin: 3,
    frequency: 1,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // ʒ: measure
  {
    phoneme: "ʒ",
    form: "s",
    origin: 3,
    frequency: 10,
    cluster: 0,
    startWord: 0,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʒ",
    form: "si",
    origin: 3,
    frequency: 10,
    onset: 0,
    cluster: 0,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "ʒ",
    form: "z",
    origin: 3,
    frequency: 10,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʒ",
    form: "g",
    origin: 3,
    frequency: 10,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʒ",
    form: "ge",
    origin: 3,
    frequency: 10,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ʒ",
    form: "dge",
    origin: 3,
    frequency: 10,
    onset: 0,
    startWord: 0,
    midWord: 0,
    endWord: 1,
  },

  // h: hat
  {
    phoneme: "h",
    form: "h",
    origin: 0,
    frequency: 50,
    coda: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  // who, whole
  {
    phoneme: "h",
    form: "wh",
    origin: 0,
    frequency: 1,
    coda: 0,
    startWord: 1,
    midWord: 0,
    endWord: 0,
  },
];
