import type { SplitVowelSupport } from "../../core/spelling-split-policy.js";

/** Registered Q14a output relations; weights and input ownership do not imply these licenses. */
export const englishSplitVowelSupports: SplitVowelSupport[] = [
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["b"], "written": "b"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["d"], "written": "d"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["f"], "written": "f"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["k"], "written": "k"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["l"], "written": "l"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["m"], "written": "m"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["n"], "written": "n"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["p"], "written": "p"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["s"], "written": "c"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["t"], "written": "t"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["v"], "written": "v"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["z"], "written": "z"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["ð"], "written": "th"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["s", "t"], "written": "st"}, "marker": "e"},
  {"vowel": {"sound": "eɪ", "component": "a"}, "coda": {"sounds": ["n", "dʒ"], "written": "ng"}, "marker": "e"},
  {"vowel": {"sound": "i:", "component": "e"}, "coda": {"sounds": ["d"], "written": "d"}, "marker": "e"},
  {"vowel": {"sound": "i:", "component": "e"}, "coda": {"sounds": ["n"], "written": "n"}, "marker": "e"},
  {"vowel": {"sound": "i:", "component": "e"}, "coda": {"sounds": ["m"], "written": "m"}, "marker": "e"},
  {"vowel": {"sound": "i:", "component": "e"}, "coda": {"sounds": ["z"], "written": "s"}, "marker": "e"},
  {"vowel": {"sound": "i:", "component": "e"}, "coda": {"sounds": ["v"], "written": "v"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["m"], "written": "m"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["f"], "written": "f"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["k"], "written": "k"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["l"], "written": "l"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["n"], "written": "n"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["p"], "written": "p"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["s"], "written": "c"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["t"], "written": "t"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["v"], "written": "v"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["z"], "written": "z"}, "marker": "e"},
  {"vowel": {"sound": "aɪ", "component": "i"}, "coda": {"sounds": ["ð"], "written": "th"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["b"], "written": "b"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["d"], "written": "d"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["p"], "written": "p"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["l"], "written": "l"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["m"], "written": "m"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["n"], "written": "n"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["t"], "written": "t"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["z"], "written": "s"}, "marker": "e"},
  {"vowel": {"sound": "əʊ", "component": "o"}, "coda": {"sounds": ["ð"], "written": "th"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["d"], "written": "d"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["b"], "written": "b"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["k"], "written": "k"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["l"], "written": "l"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["n"], "written": "n"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["s"], "written": "s"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["t"], "written": "t"}, "marker": "e"},
  {"vowel": {"sound": "u", "component": "u"}, "coda": {"sounds": ["dʒ"], "written": "g"}, "marker": "e"},
];
