/**
 * Simple vowel graphemes.
 * 
 * Includes monophthongs (single vowel sounds):
 * - High vowels: i: (sheep), ɪ (sit), ʊ (book), u (blue)
 * - Mid vowels: e (red), ɛ (let), ə (the), ɜ (bed), ɚ (her), ʌ (cup)
 * - Low vowels: æ (cat), ɑ (father), ɔ (ball), o (hope)
 */

import { Grapheme } from "../../types.js";

export const vowelGraphemes: Grapheme[] = [
  // i: sheep
  {
    phoneme: "i:",
    form: "ee",
    origin: 0,
    frequency: 50,
    startWord: 0,
    midWord: 4,
    endWord: 1,
  },
  {
    phoneme: "i:",
    form: "ea",
    origin: 0,
    frequency: 50,
    startWord: 20,
    midWord: 3,
    endWord: 1,
  },
  {
    phoneme: "i:",
    form: "e",
    origin: 0,
    frequency: 1,
    startWord: 100,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "i:",
    form: "y",
    origin: 1,
    frequency: 1,
    startWord: 0,
    midWord: 1,
    endWord: 100,
  },
  {
    phoneme: "i:",
    form: "ie",
    origin: 0,
    frequency: 2,
    startWord: 0,
    midWord: 5,
    endWord: 2,
  },
  {
    phoneme: "i:",
    form: "ei",
    origin: 0,
    frequency: 2,
    startWord: 10,
    midWord: 1,
    endWord: 0,
  },
  // people
  {
    phoneme: "i:",
    form: "eo",
    origin: 1,
    frequency: 1,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },

  // ɪ: sit
  {
    phoneme: "ɪ",
    form: "i",
    origin: 0,
    frequency: 1000,
    startWord: 5,
    midWord: 10,
    endWord: 0.01,
  },
  // myth
  {
    phoneme: "ɪ",
    form: "y",
    origin: 1,
    frequency: 1,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },
  // build
  {
    phoneme: "ɪ",
    form: "ui",
    origin: 1,
    frequency: 1,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },

  // e: red
  {
    phoneme: "e",
    form: "e",
    origin: 0,
    frequency: 250,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  // bread
  {
    phoneme: "e",
    form: "ea",
    origin: 0,
    frequency: 10,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },
  // said
  {
    phoneme: "e",
    form: "ai",
    origin: 0,
    frequency: 5,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },
  // friend
  {
    phoneme: "e",
    form: "ie",
    origin: 0,
    frequency: 3,
    startWord: 0,
    midWord: 1,
    endWord: 0,
  },

  // ɛ: let
  {
    phoneme: "ɛ",
    form: "e",
    origin: 0,
    frequency: 1000,
    startWord: 10,
    midWord: 10,
    endWord: 5,
  },
  // threat
  {
    phoneme: "ɛ",
    form: "ea",
    origin: 0,
    frequency: 10,
    onset: 0,
    startWord: 0,
    midWord: 10,
    endWord: 5,
  },

  // æ: cat
  {
    phoneme: "æ",
    form: "a",
    origin: 0,
    frequency: 10,
    startWord: 10,
    midWord: 10,
    endWord: 5,
  },

  // ɑ: father
  {
    phoneme: "ɑ",
    form: "a",
    origin: 0,
    frequency: 1000,
    startWord: 10,
    midWord: 10,
    endWord: 5,
  },
  {
    phoneme: "ɑ",
    form: "ah",
    origin: 4,
    frequency: 10,
    startWord: 0,
    midWord: 5,
    endWord: 10,
  },
  {
    phoneme: "ɑ",
    form: "aa",
    origin: 4,
    frequency: 1,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "ɑ",
    form: "au",
    origin: 0,
    frequency: 40,
    startWord: 1,
    midWord: 10,
    endWord: 0,
  },
  {
    phoneme: "ɑ",
    form: "aue",
    origin: 0,
    frequency: 40,
    startWord: 1,
    midWord: 10,
    endWord: 10,
  },

  // ɔ: ball
  {
    phoneme: "ɔ",
    form: "o",
    origin: 0,
    frequency: 10,
    startWord: 10,
    midWord: 10,
    endWord: 5,
  },
  {
    phoneme: "ɔ",
    form: "aw",
    origin: 0,
    frequency: 1,
    onset: 0,
    startWord: 0,
    midWord: 1,
    endWord: 2,
  },

  // o: hope
  {
    phoneme: "o",
    form: "o",
    origin: 0,
    frequency: 100,
    startWord: 10,
    midWord: 10,
    endWord: 1,
  },
  {
    phoneme: "o",
    form: "oa",
    origin: 0,
    frequency: 100,
    startWord: 1,
    midWord: 10,
    endWord: 0,
  },
  {
    phoneme: "o",
    form: "ow",
    origin: 0,
    frequency: 2,
    startWord: 0,
    midWord: 2,
    endWord: 10,
  },
  {
    phoneme: "o",
    form: "oe",
    origin: 0,
    frequency: 40,
    startWord: 0,
    midWord: 0,
    endWord: 3,
  },
  {
    phoneme: "o",
    form: "ough",
    origin: 4,
    frequency: 10,
    onset: 0,
    startWord: 0,
    midWord: 1,
    endWord: 2,
  },
  {
    phoneme: "o",
    form: "ew",
    origin: 0,
    frequency: 1,
    onset: 0,
    startWord: 0,
    midWord: 0,
    endWord: 1,
  },

  // ʊ: book
  {
    phoneme: "ʊ",
    form: "oo",
    origin: 0,
    frequency: 10,
    onset: 0,
    startWord: 0,
    midWord: 2,
    endWord: 2,
  },
  {
    phoneme: "ʊ",
    form: "u",
    origin: 0,
    frequency: 100,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // u: blue
  {
    phoneme: "u",
    form: "ou",
    origin: 1,
    frequency: 2,
    startWord: 0,
    midWord: 10,
    endWord: 0,
  },
  {
    phoneme: "u",
    form: "oo",
    origin: 0,
    frequency: 10,
    startWord: 0,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "u",
    form: "u",
    origin: 0,
    frequency: 10,
    startWord: 10,
    midWord: 10,
    endWord: 2,
  },
  {
    phoneme: "u",
    form: "ue",
    origin: 0,
    frequency: 10,
    startWord: 0,
    midWord: 5,
    endWord: 50,
  },
  {
    phoneme: "u",
    form: "ew",
    origin: 0,
    frequency: 10,
    startWord: 1,
    midWord: 5,
    endWord: 30,
  },

  // ʌ: cup
  {
    phoneme: "ʌ",
    form: "u",
    origin: 0,
    frequency: 1000,
    startWord: 1,
    midWord: 1,
    endWord: 0,
  },
  {
    phoneme: "ʌ",
    form: "uh",
    origin: 0,
    frequency: 30,
    startWord: 1,
    midWord: 4,
    endWord: 1,
  },

  // ə: the (schwa)
  {
    phoneme: "ə",
    form: "e",
    origin: 0,
    frequency: 500,
    startWord: 5,
    midWord: 10,
    endWord: 1,
  },
  {
    phoneme: "ə",
    form: "a",
    origin: 0,
    frequency: 4,
    startWord: 1000,
    midWord: 5,
    endWord: 9,
  },
  {
    phoneme: "ə",
    form: "o",
    origin: 0,
    frequency: 1,
    startWord: 1,
    midWord: 5,
    endWord: 1,
  },
  {
    phoneme: "ə",
    form: "ou",
    origin: 0,
    frequency: 1,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ə",
    form: "u",
    origin: 0,
    frequency: 10,
    startWord: 5,
    midWord: 10,
    endWord: 0,
  },

  // ɜ: bed, said, execute
  {
    phoneme: "ɜ",
    form: "e",
    origin: 0,
    frequency: 100,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },
  {
    phoneme: "ɜ",
    form: "ai",
    origin: 0,
    frequency: 50,
    onset: 0,
    startWord: 1,
    midWord: 1,
    endWord: 1,
  },

  // ɚ: her, letter, butter (rhoticized schwa)
  {
    phoneme: "ɚ",
    form: "er",
    origin: 0,
    frequency: 300,
    startWord: 1,
    midWord: 50,
    endWord: 100,
  },
  {
    phoneme: "ɚ",
    form: "ur",
    origin: 0,
    frequency: 100,
    startWord: 10,
    midWord: 30,
    endWord: 80,
  },
  {
    phoneme: "ɚ",
    form: "or",
    origin: 3,
    frequency: 300,
    startWord: 0,
    midWord: 20,
    endWord: 50,
  },
  {
    phoneme: "ɚ",
    form: "ar",
    origin: 3,
    frequency: 80,
    startWord: 1,
    midWord: 10,
    endWord: 40,
  },
  {
    phoneme: "ɚ",
    form: "re",
    origin: 1,
    frequency: 50,
    startWord: 0,
    midWord: 5,
    endWord: 100,
  },
  {
    phoneme: "ɚ",
    form: "ure",
    origin: 3,
    frequency: 30,
    startWord: 0,
    midWord: 10,
    endWord: 80,
  },
];
